class Download < ApplicationRecord
  belongs_to :request
  belongs_to :download_client, optional: true
  has_many :request_events, dependent: :nullify

  enum :status, {
    queued: 0,
    downloading: 1,
    paused: 2,
    completed: 3,
    failed: 4
  }

  validates :status, presence: true

  scope :active, -> { where(status: [:queued, :downloading]) }

  def active?
    queued? || downloading?
  end

  def progress_percentage
    "#{progress}%"
  end

  # Note: completed? is auto-generated by Rails enum, no need to define it
end
